### ISSUE TITLE
Make an open source summit journey vlog video

### ISSUE THREAD

**Issue by univerone** [wechaty/summer-of-wechaty#24]
Make a vlog video(with help from @rickyyin98 ) and publish it on YouTube

#26

**Comment by huan** [comment]
Kindly ping @univerone

**Comment by univerone** [comment]
I'll get started this month

> Kindly ping @univerone

**Comment by huan** [comment]
Hi @univerone , I hope your vlog can be published in the following days, looking forward to seeing it!

**Comment by huan** [comment]
kingly ping @univerone

**Comment by wj-Mcat** [comment]
ping @univerone

**Comment by huan** [comment]
@wj-Mcat It seems that the `ping` from your hand had worked! :+1: 

Cheers!

**Comment by univerone** [comment]
The video has been published at https://youtu.be/0ARx1cCf5p0

**Comment by huan** [comment]
Cheers!

Thank you @univerone for this great vlog!

Could we add this video embedded to one of our blog posts, for example, https://wechaty.js.org/2020/12/08/python-wechaty-open-source-journey/ , because that will make it be visible for more readers?

**Comment by huan** [comment]
We are 100% completed now, cheers!

Thank you very much @wj-Mcat @rickyyin98 @univerone for all the efforts in our Summer 2020 event, it can not archive today's success without any of you. Appreciate it!

![image](https://user-images.githubusercontent.com/1361891/108201861-4cd62f80-715b-11eb-9228-bb7d3ef6633e.png)

**Comment by univerone** [comment]
> Cheers!
> 
> Thank you @univerone for this great vlog!
> 
> Could we add this video embedded to one of our blog posts, for example, https://wechaty.js.org/2020/12/08/python-wechaty-open-source-journey/ , because that will make it be visible for more readers?

Of course, I have added the video to Wechaty playlist, and we could embed the talk videos and relevant slides also.

**Comment by huan** [comment]
Awesome, I saw you have added this vlog to the playlist, that's terrific!

Could you also create a PR to add this vlog to the https://wechaty.js.org/2020/12/08/python-wechaty-open-source-journey/ so that it can be played inside the blog post?

**Comment by univerone** [comment]
> Awesome, I saw you have added this vlog to the playlist, that's terrific!
> 
> Could you also create a PR to add this vlog to the https://wechaty.js.org/2020/12/08/python-wechaty-open-source-journey/ so that it can be played inside the blog post?

OK!
