### ISSUE TITLE
Preparations for Google Summer of Code 2021 (GSoC)

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/summer-of-wechaty#30]
关于 [Google Summer of Code](https://summerofcode.withgoogle.com/) 所有的活动细节的筹备会在此Issue中来记录并安排，共建透明&开放&包容的wechaty社区

也非常欢迎各位志愿者参与到此次[Google Summer of Code](https://summerofcode.withgoogle.com/)的活动当中来，在此过程中你将接触如何运营开源社区活动、与谷歌活动方协调与沟通以及一大群有趣的人，非常欢迎各位的到来。 

> 联系方式我稍后会在此评论区给出。

**Comment by huan** [comment]
Close this issue because the GSoC application has not been accepted this year.

Let's prepare to apply again in 2022! :muscle:
