### ISSUE TITLE
Google Season of Docs Application

### ISSUE THREAD

**Issue by huan** [wechaty/summer-of-wechaty#72]
We have filled the [Organization Application for 2021 Season of Docs](http://goo.gle/3qVxArQ), and will send PR to <https://github.com/google/season-of-docs/blob/main/2021-participants/interested-organizations.md>

For any technical writer who is interested in participating in Wechaty GSoD 2021, please read our GSoD proposal at <https://wechaty.js.org/docs/gsod/2021> for details.

We are accepting proposals from technical writers in the following two weeks, please send your proposal and CV to our email list wechaty@googlegroups.com then join our [Gitter channel](https://gitter.im/wechaty/wechaty) to say hi to the community!

**Comment by huan** [comment]
## Update Apr 17, 2021

We have accepted as one of the 30 top open-source projects by [GSoD 2021](https://developers.google.com/season-of-docs/docs/participants)!

![image](https://user-images.githubusercontent.com/1361891/115141855-1e000b00-a071-11eb-9689-91a09fe40353.png)

**Comment by sajenjeshan1222** [comment]
Hi I would like to do docs (Create easy to learn tutorials for beginner users of Wechaty) to this org by Google season of Docs. I have experience working regarding coding chatbots, NLP, and other deep learning projects

**Comment by huan** [comment]
Our technical writers are on boarding now: https://github.com/wechaty/wechaty.js.org/issues/817
