### ISSUE TITLE
OSPP Application in English

### ISSUE THREAD

**Issue by Roxanne718** [wechaty/summer-of-wechaty#73]
We have submitted a community presentation (in Chinese) to the OSPP Organizing Committee and received feedback, and if we intend to introduce bilingual community introductions in English and Chinese on the OSPP website, we need to write and submit a community presentation in English.

**Comment by huan** [comment]
Thank you very much for the effort to pushing our application for Summer 2021 moving forward!

Please feel free to let me know if you need any helps from me.
